"""
Ergonomics analyzer configuration
"""

POOR_POSTURE_ANGLE = 20
POSTURE_ALERT_INTERVAL = 30
POSTURE_CRITICAL_DURATION= 900

BLINK_RATE_MIN = 10
BLINK_ALERT_INTERVAL = 60

CAMERA_DEVICE_ID = 0
CAMERA_FPS = 30
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480

PIPE_NAME = r'\\.\pipe\ergonomics_pipe'

NECK_ANGLE_THRESHOLD = 20
SHOULDER_ANGLE_THRESHOLD = 15
